### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mstenta** [mstenta/farmOS-conventions#1]
- [x] Initial commit / README.md
- [x] Introduce to community and invite comments
- [ ] #3
- [ ] #2
- [ ] #4
- [ ] #5
- [ ] #6
- [ ] Establish and document recommended process for development of community/custom conventions and how they can converge over time
- [ ] Initial set of conventions
    - [ ] Soil test / water test
    - [ ] ...
- [ ] ...
- [ ] Move this repo to github.com/farmOS/conventions
- [ ] Publish conventions to farmOS.org/model/convention/*

**Comment by mstenta** [comment]
> Introduce to community and invite comments

https://farmos.discourse.group/t/documenting-conventions/1263

**Comment by mstenta** [comment]
I swapped #3 and #2 in the roadmap because the current template proposal presumes the ID format that I proposed in #3.
